In [7]:
import pandas as pd
df1 = pd.DataFrame({
        '姓名':['张三','李四'],
        '年龄':[18,19],
        '性别':['男','女']
}
)
df1

   姓名  年龄 性别
0  张三  18  男
1  李四  19  女

In [6]:
df2 = pd.DataFrame(
    [
        ['张三',18,'男'],
        ['李四',19,'女']
    ],
    columns=['姓名','年龄','性别']
)
df2

   姓名  年龄 性别
0  张三  18  男
1  李四  19  女

In [8]:
df3 = pd.DataFrame(
    [
        ['张三',18,'男'],
        ['李四',19,'女']
    ],
    columns=['姓名','年龄','性别'],index=[1,2]
)
# DataFrame常见属性
df3.columns.tolist() # 列名
# df3.index.tolist() # 行索引
# df3.values.tolist() # 值
# df3.size #元素个数
# df3.shape # 行数和列数
# df3.dtypes # 列数据类型

['姓名', '年龄', '性别']

In [16]:
# Series创建
s1 = pd.Series([1,2,3,4,5])

s2 = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

s3 = pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5})


# Series常见属性
s1.index.tolist()
s1.values.tolist()
s1.size
s1.shape
s1.dtype

dtype('int64')